pdm server
Traceback (most recent call last):
  File "/mnt/e/development/projects/backend/python-django/django-auth/./src/manage.py", line 22, in <module>
    main()
    ~~~~^^
  File "/mnt/e/development/projects/backend/python-django/django-auth/./src/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/mnt/e/development/projects/backend/python-django/django-auth/.venv/lib/python3.13/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
    ~~~~~~~~~~~~~~~^^
  File "/mnt/e/development/projects/backend/python-django/django-auth/.venv/lib/python3.13/site-packages/django/core/management/__init__.py", line 382, in execute
    settings.INSTALLED_APPS
  File "/mnt/e/development/projects/backend/python-django/django-auth/.venv/lib/python3.13/site-packages/django/conf/__init__.py", line 81, in __getattr__
    self._setup(name)
    ~~~~~~~~~~~^^^^^^
  File "/mnt/e/development/projects/backend/python-django/django-auth/.venv/lib/python3.13/site-packages/django/conf/__init__.py", line 68, in _setup
    self._wrapped = Settings(settings_module)
                    ~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/mnt/e/development/projects/backend/python-django/django-auth/.venv/lib/python3.13/site-packages/django/conf/__init__.py", line 166, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/home/alex-candido/.local/share/pdm/python/cpython@3.13.2/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/mnt/e/development/projects/backend/python-django/django-auth/src/django_app/__init__.py", line 3, in <module>
    from .container import Container
  File "/mnt/e/development/projects/backend/python-django/django-auth/src/django_app/container.py", line 5, in <module>
    from django_app.modules.v1.users.container import UserContainer
  File "/mnt/e/development/projects/backend/python-django/django-auth/src/django_app/modules/v1/users/container.py", line 4, in <module>
    from .repositories import UserRepository
  File "/mnt/e/development/projects/backend/python-django/django-auth/src/django_app/modules/v1/users/repositories.py", line 9, in <module>
    from .filters import UserFilter
  File "/mnt/e/development/projects/backend/python-django/django-auth/src/django_app/modules/v1/users/filters.py", line 4, in <module>
    from .models import User
  File "/mnt/e/development/projects/backend/python-django/django-auth/src/django_app/modules/v1/users/models.py", line 5, in <module>
    from django.contrib.auth.models import AbstractUser
  File "/mnt/e/development/projects/backend/python-django/django-auth/.venv/lib/python3.13/site-packages/django/contrib/auth/models.py", line 5, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/mnt/e/development/projects/backend/python-django/django-auth/.venv/lib/python3.13/site-packages/django/contrib/auth/base_user.py", line 43, in <module>
    class AbstractBaseUser(models.Model):
    ...<123 lines>...
            )
  File "/mnt/e/development/projects/backend/python-django/django-auth/.venv/lib/python3.13/site-packages/django/db/models/base.py", line 131, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/mnt/e/development/projects/backend/python-django/django-auth/.venv/lib/python3.13/site-packages/django/apps/registry.py", line 260, in get_containing_app_config
    self.check_apps_ready()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/mnt/e/development/projects/backend/python-django/django-auth/.venv/lib/python3.13/site-packages/django/apps/registry.py", line 138, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.